In [1]:
import tensorflow as tf
import numpy as np

### Basic operations

In [2]:
a = tf.Variable(2.0)
b = tf.Variable(3.0)

In [3]:
c = tf.add(a, b)

In [4]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(c), sess.run(a))

(5.0, 2.0)


In [5]:
d_np = np.array([[2, 3], [4, 5]], dtype=np.float32)
e_np = np.array([[3, 1], [2, 1]], dtype=np.float32)
d = tf.Variable(d_np)
e = tf.Variable(e_np)

In [6]:
f = tf.multiply(d, e)
g = tf.matmul(d, e)

In [7]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print sess.run(d)
    print sess.run(e)
    print sess.run(f)
    print sess.run(g)

[[ 2.  3.]
 [ 4.  5.]]
[[ 3.  1.]
 [ 2.  1.]]
[[ 6.  3.]
 [ 8.  5.]]
[[ 12.   5.]
 [ 22.   9.]]



energy_breakdown_mat = M X N X T


In [8]:
M = 30
N = 5
T = 12
h = 2
s = 3

In [9]:
A_np = np.random.randn(M, h)
print A_np

[[ 0.6223845  -1.74872636]
 [ 0.17448214 -0.59461282]
 [-1.23357418  0.01472871]
 [ 0.83278414  0.26162015]
 [-0.638517   -0.09714385]
 [ 2.14427135  0.35091822]
 [-0.32745181 -0.15306017]
 [-2.9957434  -1.79565558]
 [-0.91165998 -2.32008211]
 [ 2.31118062  0.02653387]
 [ 1.56107231 -0.6095168 ]
 [ 0.07346232 -0.82808511]
 [ 0.84202569 -0.51452046]
 [-0.0829432  -0.06512118]
 [ 0.27931783 -0.3814122 ]
 [-1.0111435   1.11976724]
 [ 0.11994977  0.1456507 ]
 [-0.31103834 -1.10948351]
 [-0.46724916 -1.51674096]
 [-0.06299639  0.04685958]
 [-0.26549287  0.86807753]
 [-0.1416586   0.70983295]
 [ 1.91923691  0.06434215]
 [-0.05851666  1.37427152]
 [-0.79582505  0.08355399]
 [-0.5437043  -0.12157113]
 [-1.32025398 -0.40039427]
 [-0.50850472  0.92890264]
 [ 0.13462937 -0.34503665]
 [ 0.11500549  0.5778354 ]]


In [11]:
C_np = np.random.randn(T, s).transpose()


In [13]:
B_np = np.random.randn(h, N, s)


In [14]:
A_tf = tf.Variable(A_np)
C_tf = tf.Variable(C_np)
B_tf = tf.Variable(B_np)

In [15]:
np.tensordot(np.tensordot(A_np, B_np, axes=1), C_np, axes=1).shape

(30, 5, 12)

In [16]:
np.tensordot(A_np, B_np, axes=1).shape

(30, 5, 3)

In [17]:
A_np.shape

(30, 2)

In [18]:
B_np.shape

(2, 5, 3)

In [19]:
A_np[0]

array([ 0.6223845 , -1.74872636])

In [20]:
B_np[:,0,:]

array([[ 1.02056664, -0.27667905, -0.67220086],
       [-0.00733637, -0.90718505, -1.95303756]])

In [21]:
C_np[:,0]

array([-0.6940274 , -0.52600197, -0.46357418])

In [22]:
1.418*-1.58-1.04*-1.205

-0.9872399999999999

In [23]:
np.dot(A_np[0], B_np[:,0,:]).dot(C_np[:,0])

-2.5829345400343255

In [25]:
np.tensordot(np.tensordot(A_np, B_np, axes=1), C_np, axes=1)

array([[[-2.58293454, -0.71922813, -0.15713245, ..., -0.68642722,
          1.17335826, -2.66554589],
        [ 1.93613538, -7.53164117,  6.60525502, ...,  0.1957339 ,
          6.35241106,  4.76997643],
        [-4.65280005, -2.59904245, -0.32629984, ..., -2.07109718,
          3.531974  , -4.11884878],
        [ 3.98291626,  0.14978811,  2.54272802, ...,  2.11833724,
         -1.30070149,  4.11021758],
        [ 2.17678729, -5.06534726,  3.8953635 , ..., -0.21685044,
          4.2758136 ,  4.36579821]],

       [[-0.86893644, -0.22303241, -0.03339665, ..., -0.20528456,
          0.36981774, -0.910701  ],
        [ 0.6464761 , -2.43710664,  2.14900545, ...,  0.07271364,
          2.05006712,  1.56471924],
        [-1.62824198, -0.8381626 , -0.20165259, ..., -0.74356158,
          1.17896469, -1.45941302],
        [ 1.32118211,  0.06378298,  0.87145144, ...,  0.73146487,
         -0.45311468,  1.35009343],
        [ 0.77790728, -1.7081533 ,  1.36154741, ..., -0.03650522,
          1.42

In [26]:
AB_tf = tf.tensordot(A_tf, B_tf,axes = [[1], [0]])


In [27]:
A_tf.get_shape()

TensorShape([Dimension(30), Dimension(2)])

In [28]:
B_tf.get_shape()

TensorShape([Dimension(2), Dimension(5), Dimension(3)])

In [29]:
AB_tf.get_shape()

TensorShape([Dimension(30), Dimension(5), Dimension(3)])

In [30]:
C_tf.get_shape()

TensorShape([Dimension(3), Dimension(12)])

In [34]:
AB_tf_C_tf = tf.tensordot(AB_tf, C_tf, axes=[[2], [0]])

In [35]:
AB_tf_C_tf.get_shape()

TensorShape([Dimension(30), Dimension(5), Dimension(12)])

In [40]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    ABC_tf = sess.run(AB_tf_C_tf)

In [41]:
import pandas as pd
pd.DataFrame(ABC[0])

0         1         2         3         4         5         6   \
0 -2.582935 -0.719228 -0.157132 -2.449951 -0.143129 -1.932391 -1.625801   
1  1.936135 -7.531641  6.605255  0.262827  3.408539 -3.909649  9.065041   
2 -4.652800 -2.599042 -0.326300 -5.189535 -1.371790 -4.097325  1.515848   
3  3.982916  0.149788  2.542728  4.322750  2.922008  1.993915 -1.014298   
4  2.176787 -5.065347  3.895364  0.577970  1.238821 -1.955102  9.201931   

         7         8         9         10        11  
0  1.670596 -1.895155 -0.686427  1.173358 -2.665546  
1 -6.990225  0.342118  0.195734  6.352411  4.769976  
2 -0.755798 -4.715680 -2.071097  3.531974 -4.118849  
3  0.720831  4.374889  2.118337 -1.300701  4.110218  
4 -7.510870  0.016626 -0.216850  4.275814  4.365798

In [42]:
ABC_np = np.tensordot(np.tensordot(A_np, B_np, axes=1), C_np, axes=1)

In [43]:
pd.DataFrame(ABC_np[0])

0         1         2         3         4         5         6   \
0 -2.582935 -0.719228 -0.157132 -2.449951 -0.143129 -1.932391 -1.625801   
1  1.936135 -7.531641  6.605255  0.262827  3.408539 -3.909649  9.065041   
2 -4.652800 -2.599042 -0.326300 -5.189535 -1.371790 -4.097325  1.515848   
3  3.982916  0.149788  2.542728  4.322750  2.922008  1.993915 -1.014298   
4  2.176787 -5.065347  3.895364  0.577970  1.238821 -1.955102  9.201931   

         7         8         9         10        11  
0  1.670596 -1.895155 -0.686427  1.173358 -2.665546  
1 -6.990225  0.342118  0.195734  6.352411  4.769976  
2 -0.755798 -4.715680 -2.071097  3.531974 -4.118849  
3  0.720831  4.374889  2.118337 -1.300701  4.110218  
4 -7.510870  0.016626 -0.216850  4.275814  4.365798

In [44]:
np.allclose(ABC_np, ABC_tf)

True